language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      env: MATRIX="CC=gcc-8 && CXX=g++-8"
    - os: linux
      dist: xenial
      compiler: clang
      env: MATRIX="CC=clang-8 && CXX=clang++-8"

script:
  - 'eval $MATRIX'
  - 'mkdir -p build'
  - 'cd build'
  - 'cmake ..'
  - 'cd ..'
  - 'cmake --build build'

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-8
      - sourceline: ppa:ubuntu-sdk-team/ppa
    packages:
      - qt5-default
      - g++-8
      - clang-8
      - libc++-8-dev
      - libc++abi-8-dev
